# Generated by Django 4.2.6 on 2024-01-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['st_name'], 'verbose_name': 'student'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='st_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='st_age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='st_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='st_name',
        ),
    ]
