# Generated by Django 4.2.6 on 2024-01-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sub_sub_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_marks',
            old_name='st',
            new_name='st_name',
        ),
        migrations.RenameField(
            model_name='sub_marks',
            old_name='sub',
            new_name='sub_name',
        ),
        migrations.AlterUniqueTogether(
            name='sub_marks',
            unique_together={('st_name', 'sub_name')},
        ),
    ]
