# Generated by Django 4.2.6 on 2024-01-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_st_sub_marks_st_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_marks',
            options={'ordering': ['st_name']},
        ),
    ]
